name: Build
# https://github.com/marketplace/actions/cosign-installer
on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]
  release:
    types: [created]
    
env:
  IMAGE_NAME: demoapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup ko
      uses: imjasonh/setup-ko@v0.6

    - name: Install Cosign
      uses: sigstore/cosign-installer@main

    - name: Log in to ghcr registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        echo "${{ secrets.GITHUB_TOKEN }}" | ko login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the image with ko
      run: |
        ko build -t ko
      # env:
      #  KO_DOCKER_REPO: ghcr.io/eumel8/oro-demoapp

    - name: Build the image with docker
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Push & Sign image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo "{{ github.ref.type }}"
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        cosign sign --key env://COSIGN_KEY $IMAGE_ID:$VERSION
        cosign sign --key env://COSIGN_KEY ghcr.io/eumel8/oro-demoapp/main:ko
      env:
        COSIGN_KEY: ${{secrets.COSIGN_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

    - name: Push & Sign image release
      if: github.ref.type == 'tag'
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=${GITHUB_REF_NAME}
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        cosign sign --key env://COSIGN_KEY $IMAGE_ID:$VERSION
      env:
        COSIGN_KEY: ${{secrets.COSIGN_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
